version: '2'

services:
  #Redis
  redis:
    image: redis:3.2

  #Web app
  web:
    build: .
    command: ./run_web.sh
    volumes:
      - ./app:/app
    expose:
      - '5000'
    links:
      - redis

  #Celery worker
  celery:
    build: .
    command: ./run_celery.sh
    volumes:
      - ./app:/app
    links:
      - redis

